### ISSUE TITLE
名称

### ISSUE THREAD

**Issue by sh4869** [Daruin/Daruin#2]

**Comment by sh4869** [comment]
現状の名前だとダサすぎる

duinoという名前をつけるのは出来るだけさけてくれというのが公式側の見解らしいです
http://trac.switch-science.com/wiki/ArduinoCompatible

**Comment by sh4869** [comment]
名称決めたら適当にチーム名決めてレポジトリを個人管理から組織管理にするつもりです。特に実用性に問題はないはず(URLが変わるだけ)

**Comment by sana37** [comment]
おれが考えてもろくなの思いつかないと思う…
今Arduinoを並べ替えてDaruinoに思い至った；

**Comment by sh4869** [comment]
だるいの… 星井美希かな?

**Comment by sh4869** [comment]
いいかもしれない(他に思いつかなくなった)

**Comment by sana37** [comment]
おれは何でもいいや

**Comment by sh4869** [comment]
Daruinの方が響きよさそう(?)

**Comment by sana37** [comment]
日本語っぽさが減って良くなった

**Comment by sh4869** [comment]
じゃあそれで行こう

**Comment by sana37** [comment]
おｋ

**Comment by sh4869** [comment]
移しました。Orgから招待が来ているはずなので許可してください

**Comment by sh4869** [comment]
あとこのissueは閉じますね
